ALTER TABLE schedule_entries
  ADD COLUMN IF NOT EXISTS revenue_cash NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS revenue_cashless NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS revenue_total NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS ticket_price NUMERIC(8,2) DEFAULT 33.00,
  ADD COLUMN IF NOT EXISTS tickets_sold INTEGER;
